// Saga
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";

export const SPELL_CORRECTION = "SPELL_CORRECTION";
export const INTENT_DETECTION = "INTENT_DETECTION";

// Reducer
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const SPELL_CORRECTION_RECEIVED = "SPELL_CORRECTION_RECEIVED";
export const INTENT_DETECTION_RECEIVED = "INTENT_DETECTION_RECEIVED";
