version: "3.6"
services:
  app:
    image: quochung5c/chatops-server
    environment:
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27018:27018"
    volumes: 
      - .docker/data/db:/data/db
    restart: unless-stopped
